### PR TITLE
modified readme title

### LINKED ISSUE #1: Change Readme title

### PR DESCRIPTION
**Pull request by lefameuxbeding**
Closes #1

### CODE REVIEW

**Comment by vibingyeti** [comment]
seems good to me

**Comment by ouzzy92** [comment]
cool

**Review by divcamillediv — APPROVED** [review]
seems good to me

**Review by ouzzy92 — APPROVED** [review]
Approuved

**Review by mohamedThameurSassi — APPROVED** [review]
pas assez travaillé recommence

**Pull request merged**
